config/routes.rb
Rails.application.routes.draw do
  get 'infos/profile'

  get 'infos/contact'

  devise_for :users
  resources :posts

  resources :post do
  	member do
  		put "like", to: "posts#upvote"
  	end
  end
  		
  root to: 'posts#index'

  get "/:newsletter" => 'emailapi#newsletter'
  post 'emailapi/subscribe' => 'emailapi#subscribe'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
	self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	has_attached_file :image, styles: { large: "800x800>", medium: "400x400>", thumb: "150x150#" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/, :size => { :in => 0..3000.kilobytes }

	acts_as_votable

	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  after_create :subscribe_user_to_mailing_list

  private

  def subscribe_user_to_mailing_list
  	SubscribeUserToMailingListJob.perform_later(self)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me, :avatar) }
  	devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
  	devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password, :avatar) }
  end
  
end

app/controllers/emailapi_controller.rb
class EmailapiController < ApplicationController
	def newsletter
		render params[:newsletter]
	end

	def subscribe
		email = params[:email][:address]

		gb = Gibbon::Request.new(api_key: "7fd5c6c2ae53985888bbfa8a2ab149f6-us14")

		gb.lists("1367b2dcb8").members.create(
			body: {
				email_address: email,
				status: "subscribed",
				})
		redirect_to root_path

	end
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]

  def profile
  end

  def contact
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
  	@posts = Post.all.order("created_at DESC").paginate(page: params[:page], per_page: 4)
  end

  def new
  	@post = current_user.posts.build
  end

  def create
  	@post = current_user.posts.build(post_params)

  	if @post.save
  		redirect_to @post
  	else
  		render 'new'
  	end
  end

  def show
  end

  def edit
  end

  def update
  	if @post.update(post_params)
  		redirect_to @post
  	else
  		render 'edit'
  	end
  end


  def destroy
  	@post.destroy
  	redirect_to root_path
  end

  def upvote
    @post = Post.find(params[:id])
    @post.liked_by current_user
    redirect_to :back
  end

  private

  def find_post
  	@post = Post.find(params[:id])
  end

  def post_params
  	params.require(:post).permit(:title, :body, :image)
  end

  def after_sign_out_path_for(resource_or_scope)
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emailapi_helper.rb
module EmailapiHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" href="<%= asset_path 'favicon/favicon-32x32.png' %>" sizes="32x32">
<link rel="icon" type="image/png" href="<%= asset_path 'favicon/favicon-16x16.png' %>" sizes="16x16">
<link rel="manifest" href="<%= asset_path 'favicon/manifest.json' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#3b3b3b">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="apple-mobile-web-app-title" content="Andy in SF">
<meta name="application-name" content="Andy in SF">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ffffff">

app/views/emailapi/index.html.erb
<h1>Get My Awesome News Letter</h1>
<p>Give me your email and keep up to date on my cat's thoughts.</p>
<%= form_tag('/emailapi/subscribe', method: "post", id: "subscribe", remote: "true") do -%>
   <%= email_field(:email, :address, {id: "email", placeholder: "email address"}) %>
   <%= submit_tag("Sign me up!") %>
<% end %>

app/views/emailapi/newsletter.html.erb
<h1>Get My Awesome Newsletter</h1>
<p>Sign up and get monthly emails straight to your inbox!</p>
<%= form_tag('/emailapi/subscribe', method: "post", id: "subscribe", remote: "true") do -%>
   <%= email_field(:email, :address, {id: "email", placeholder: "email address"}) %>
   <%= submit_tag("Sign me up!") %>
<% end %>

app/views/infos/contact.html.erb
<h1>Infos#contact</h1>
<p>Find me in app/views/infos/contact.html.erb</p>

app/views/infos/profile.html.erb
<div class="container-fluid" style="text-align:center" id="profile_page">
	<div class="col-sm-6 col-sm-offset-3">
	    <%= image_tag current_user.avatar(:medium), class:"img-responsive img-circle center-block" %></br>
	    <h1><%= "@" + current_user.username %></h1>
	    <h4><%= current_user.email %></h4>
	    <h5><%= link_to("Edit Profile", edit_user_registration_path) %></h5>
	    <h2><%= link_to "Home", root_path, class: "btn btn-default" %></h2>
	</div>
</div>

app/views/layouts/_about.html.erb
<section class="container-fluid" id="about_page">
	<% if user_signed_in? %>
	<div class="col-sm-12">
	  <h1 class="thank_you">Thank you for following the Andy in SF Adventure!</h1>
	</div>
	<% else %>
	<%= image_tag("https://s3.amazonaws.com/andyinsfimages/andy_in_the_bay.jpg", class: "col-sm-3 img-responsive center-block", :id => "andy_profile") %>
	<div class="col-sm-6" id="what_about">
		<h2 id="whatis">What is "Andy in SF"?</h2>
		<h5 id="glad">I'm so glad you asked.</h5>
		<%= image_tag("https://s3.amazonaws.com/andyinsfimages/Icons/photo_icon.png", class: "img-responsive center-block", :id => "photo_icon") %>
		<h4 id="about_where">This is where I'll be sharing stories and reports of all the cool stuff that is happening in San Francisco, California!</h4>
		<br />
		<%= image_tag("https://s3.amazonaws.com/andyinsfimages/Icons/journal_icon.png", class: "img-responsive center-block", :id => "journal_icon") %>
		<h4 id="about_mom">It's a fun way of updating my mom on what's happening so she doesn't worry &amp; can stay focused on her naptime!</h4>
		<br />
		<%= image_tag("https://s3.amazonaws.com/andyinsfimages/Icons/footsteps_icon.png", class: "img-responsive center-block", :id => "footsteps_icon") %>
		<h4 id="about_touch">Stay up to date by reading the blog, signing up, checking in, and keeping in touch (no carrier pigeons please)!</h4>
	</div>
	<%= image_tag("https://s3.amazonaws.com/andyinsfimages/darkprofile.jpeg", class: "col-sm-3 img-responsive center-block andy_profile") %>
	<% end %>
</section>

app/views/layouts/_footer.html.erb
<div id="footer_box" class="container-fluid">
	<div class="col-sm-8 col-sm-offset-2" id="newsletter_box">
		<h5>Sign up and get monthly updates!</h5>
		<%= form_tag('/emailapi/subscribe', method: "post", id: "subscribe", remote: "true") do -%>
		   <%= email_field(:email, :address, {id: "email", placeholder: "Email Address"}) %>
		   <%= submit_tag("SIGN UP", {id: "newsletter_submit"}) %>
		<% end %>
	</div>
		<!--<div class="row">
			<div class="col-md-4 col-md-offset-4 col-xs-6 col-xs-offset-3" id="footer_links">
				<div class="col-xs-3"><h5><%= link_to "Home", root_path %></h5></div>
				<div class="col-xs-3"><h5><%= link_to "About", "#about" %></h5></div>
				<div class="col-xs-3"><h5><%= link_to "Blog", "#blog" %></h5></div>
				<div class="col-xs-3"><h5><%= link_to "Give", "https://app.moonclerk.com/pay/lkaoogze9ok", :target => "_blank" %></h5></div>
			</div>
		</div> -->
		<br />
		<div class="row footer_rights">
			<div class="col-md-4 col-md-offset-4 col-xs-8 col-xs-offset-2">
				<p>Crafted with Coffee &amp; Care by <a href="http://sightsstudios.com">Sights Studios</a>.<br />
	2017&copy;. All Rights Reserved.</p>
			</div>
		</div>
</div>

app/views/layouts/_landing.html.erb
<section id="landing_banner" class="container-fluid">
	<% if user_signed_in? %>
	<div class="col-md-6">
	  <h1>Welcome Back, @<%= current_user.username %>!</h1>
	</div>
	<% else %>
	<div class="col-md-6">
	  <h1>Welcome to Andy in SF</h1> 
	  <h5 class="col-md-8 col-xs-6">This is a blog about Andy's life in San Francisco, CA. Andy made this blog from scratch using the finest organic, free-range, paleo, gluten free code. <br> Hope you enjoy!</h5> 
	</div>
	<% end %>
</section>

app/views/layouts/_prayerpraise.html.erb
<section class="container-fluid prayer_praise_section">
	<% if user_signed_in? %>
	<div class="col-sm-12" id="prayer_praise_signup">
	  <h1 class="prayer_praise_title">Prayer &amp; Praise</h1>
	</div>
	<div class="prayer_praise_reveal_area">
		<div class="reportbox">
			<h2>Prayer</h2>
			<h5>Prayer is essential in this ongoing warfare. Pray hard and long. Pray for your brothers and sisters. <b>Ephesians 6:18</b></h5>
			<h4>&#9670;&ensp;Salvations&ensp;&#9670;</h4>
			<p>Ask that God would use me to introduce people to Him in the Bay Area.<p>
			<h4>&#9670;&ensp;Sozo Church&ensp;&#9670;</h4>
			<p>Pray for the Launch in September 2017 <br />(<a href="https://www.sozo.co/get-involved/prayer-topics">Sozo Church Prayer List</a>)<p>
			<h4>&#9670;&ensp;Provision&ensp;&#9670;</h4>
			<p>Ask that God would continue to show His provision through people's partnership.<p>
			<h4>&#9670;&ensp;Development Opportunites&ensp;&#9670;</h4>
			<p>Pray doors would open to make amazing websites for clients through <a href="https://www.sightsstudios.com">Sights Studios</a>.<p>
		</div>
		<div class="instagrambox">
			<%= link_to image_tag("https://s3.amazonaws.com/andyinsfimages/instagram_profile.png", class: "img-responsive", id: "instagram_profile"), "https://www.instagram.com/andywalt/", :target => "_blank" %>
			<%= link_to image_tag('https://s3.amazonaws.com/andyinsfimages/Icons/instagram_button_block.png'), "https://www.instagram.com/andywalt/", :target => "_blank", class: "instagram_button_block" %>
		</div>
		<div class="reportbox">
			<h2>Praise</h2>
			<h5>Sing praise-songs to God. He’s done it all! Let the whole earth know what he’s done! <br /><b>Isaiah 12:5</b></h5>
			<h4>&#9670;&ensp;Miracles&ensp;&#9670;</h4>
			<p>From provision to healing, God has been doing amazing things!<p>
			<h4>&#9670;&ensp;Untangling Knots&ensp;&#9670;</h4>
			<p>Had multiple meetings helping people far from God experience God's grace (mostly people raised in the South in SF)!</p>
			<h4>&#9670;&ensp;Food &amp; Coffee&ensp;&#9670;</h4>
			<p>God keeps opening the door for amazing connections &amp; generosity at coffee shops &amp; restaurants here!</p>
		</div>
	</div>
	<% else %>
	<div class="col-sm-12" id="prayer_praise_signup">
	  <h1 class="get_signed_up">Want to know how you can help &amp; the amazing things that are happening in San Francisco? Sign up to access the "<a href="users/sign_up">Prayer &amp; Praise</a>" page!</h1>
	</div>
	<% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Andy in SF</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', 'https://fonts.googleapis.com/css?family=Heebo:300,400,700', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'application/favicon' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <meta property="og:image" content="https://s3.amazonaws.com/andyinsfimages/andy_in_the_bay.jpg" />
    <meta property="og:description" content="In January 2017, Andy moved to beautiful San Francisco, California. He then built this amazing, wonderful, mind-blowingly cool website to be able to share with his friends and family how amazing life in SF is!" />
    <meta property="og:url"content="http://andy-in-sf.herokuapp.com" />
    <meta property="og:title" content="Andy in SF" />
  </head>
<body data-spy="scroll" data-target=".navbar">
  <% if notice %>
    <div id="notice_wrapper">
      <p class="notice"><%= notice %></p>
    </div>
  <% elsif alert %>
    <div id="notice_wrapper">
      <p class="alert"><%= alert %></p>
    </div>
  <% end %>

 	<div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <div class="navbar-inner">
        <div id="logo" class="navbar-brand"><%= link_to image_tag("https://s3.amazonaws.com/andyinsfimages/aw_logo.png", size: "50x50", class:"img-responsive img-circle"), root_path %></div>
        <div id="site-title" class="navbar-brand hidden-xs"><%= link_to "Andy in SF", root_path %></div>
        <div class="navbar-brand" id="header-navs"><a href="#about">About</a></div>
        <div class="navbar-brand" id="header-navs"><a href="#blog">Blog</a></div>
        <div class="navbar-brand" id="header-navs"><a href="https://app.moonclerk.com/pay/lkaoogze9ok" target="_blank">Give</a></div>
        <div class="navbar-header navbar-right">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle Navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"></a>
        </div>
        <div class="collapse navbar-collapse">
          <% if user_signed_in? %>
            <ul class="nav navbar-nav navbar-right nav-pills pull-right">
              <li id="avatar-thumb"><%= image_tag current_user.avatar.url(:thumb), class:"img-responsive img-circle" %></li>
              <li id="fat-menu" class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Profile
                    <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "@" + current_user.username, 'infos/profile' %></li>
                    <li><%= link_to("Edit Profile", edit_user_registration_path) %></li>
                    <li>
                      <% if current_user.try(:admin?) %>
                        <%= link_to "New Post", new_post_path %>
                      <% end %>
                    </li>
                </ul>
              </li>
              <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
            </ul>
          <% else %>
            <ul class="nav navbar-nav pull-right">
              <li><%= link_to('Sign Up', new_user_registration_path)  %></li>
              <li><%= link_to "Sign In",  new_user_session_path %></li>
            </ul>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="bannerhelp">
    <% if current_page?(root_path) %>
      <%= render 'layouts/landing' %>
    <% end %>
  </div>

  <div class="mainbody">
    <div class="container-fluid" id="about">
       <% if current_page?(root_path) %>
        <%= render 'layouts/about' %>
      <% end %>
    </div>


    <div id="blog">
      <%= yield %>
    </div>
  </div>

  <div class="mainbody">
    <div class="container-fluid" id="about">
       <% if current_page?(root_path) %>
        <%= render 'layouts/prayerpraise' %>
      <% end %>
    </div>

  <%= render 'layouts/footer' %>


</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
	<div class="form_group">
		<label for="image">Post Image</label>
		<%= f.file_field :image, class: "form-control image_adjustment" %><br>
	</div><br>

	<div class="form_group">
		<label for="title"><%= f.label :title %><br></label>
		<%= f.text_field :title, placeholder: "Make It Witty", class: "form-control" %><br>
	</div>
	<div class="form_group">
		<label for="body"><%= f.label :body %><br></label>
		<%= f.text_area :body, placeholder: "Don't Cuss", class: "form-control", rows:"10" %><br>
		<br>
	</div>
	<div class="form-actions">
		<%= f.submit class: "btn btn-default" %>
	</div>
<% end %>

app/views/posts/edit.html.erb
<div class="container">
	<div class="col-md-6 col-md-offset-3">
		<h1 class="col-md-8 col-md-offset-2">Edit Post</h1>

		<%= image_tag @post.image.url(:medium) %>

		<%= render 'form' %>

		<div class="post_navigation_links">
			<%= link_to "Back", root_path, class: "btn btn-default" %>
		</div>
	</div>
</div>

app/views/posts/index.html.erb
<div class="container-fluid" id="blog_area">
	<h1 id="blog_title">The Blog</h1>
	<div id="posts" class="transitions-enabled">
		<% @posts.each do |post| %>
			<div class="box panel panel-default">
				<%= link_to (image_tag post.image.url(:medium)), post, class: "img-responsive center-block" %>
				<%= link_to post.title, post, class: "post_title" %>
				<div class="panel-body" id="panel_body"><%= truncate(post.body, :length => 250, :omission => "...(read more).") %></div>
				<div class="btn-group">
					<%= link_to like_post_path(post), method: :put, class: "btn btn-default btn-sm" do %>
					<span class="glyphicon glyphicon-thumbs-up"></span>
						<%= post.get_upvotes.size %>
					<% end %>
				</div>
				<% if post.user == current_user %>
					<div class="crud_links">
						<%= link_to 'Edit', edit_post_path(post) %>
						<%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %>
					</div>
				<% end %>
			</div>
		<% end %>
	</div>
	<h4><%= will_paginate @posts, previous_label: "New Posts", next_label: "More Posts", class: "col-sm-12 col-sm-offset-0", :id => "paginate_selector" %></h4>
</div>

app/views/posts/new.html.erb
<div class="container">
	<div class="row">
		<br />
		<div class="col-md-3 col-md-offset-3 col-xs-10"><h1>New Post</h1></div>
		<div class="col-md-6 col-md-offset-3">
			<% if current_user.try(:admin?) %>
				<%= render 'form' %>
			<% end %>
		</div>
		<div class="col-md-2 col-md-offset-3 col-xs-1"><%= link_to "Back", root_path, class: "btn btn-default"%></div>
	</div>
</div>

app/views/posts/show.html.erb
<div class="container">
	<div class="row">
		<div>
			<%= image_tag @post.image.url(:medium), class: "img-responsive center-block", id: "post_header_image" %>
		</div>
	</div>
	<div class="col-md-6 col-md-offset-3">
		<div id="post_title">
			<h1><%= @post.title %></h1>
		</div>
	</div>
	<div id="post_body" class="row col-sm-6 col-sm-offset-3">
		<div>
			<%= simple_format(@post.body) %>
		</div>
	</div>
	<div class="row center-block" style="width:200px">
		<div class="post_navigation_links">
			<% if current_user.try(:admin?) %>
				<%= link_to "Edit Post", edit_post_path(@post) %>
				<%= link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure?"} %>
			<% end %>
		</div>
	</div>
	<div class="row center-block" id="response_box">
		<div class="col-sm-offset-3">
			<div class="col-sm-4 col-xs-6 col-xs-offset-0"><%= link_to "I'm done & wish you well!", root_path, class: "btn btn-default", :id => "read_wish" %></div>
			<div class="col-sm-4 col-xs-6 col-xs-offset-0"><%= link_to "I'm done & want to help!", "https://app.moonclerk.com/pay/lkaoogze9ok", class: "btn btn-default", :id => "read_help" %></div>
		</div>
	</div>
	<br />
</div>	